// Paper URLs mapping - collected via automated search
export const PAPER_URLS: Record<string, string> = {
  "Using Machine Learning Techniques in Console Log Analysis": "https://dl.acm.org/doi/10.1145/1629575.1629587",
  "Crowd Scene Understanding with Coherent Recurrent Neural Networks": "https://www.ijcai.org/Abstract/16/490",
  "Semi-supervised Learning for Neural Machine Translation": "https://aclanthology.org/P16-1185/",
  "Forecast Plausible Paths in Crowd Scenes": "https://www.ijcai.org/proceedings/2017/386",
  "Improving Interpretability of Deep Neural Networks with Semantic Information": "https://openaccess.thecvf.com/content_cvpr_2017/html/Dong_Improving_Interpretability_of_CVPR_2017_paper.html",
  "Joint Training for Pivot-based Neural Machine Translation": "https://www.ijcai.org/proceedings/2017/555",
  "Maximum Reconstruction Estimation for Generative Latent Variable Models": "https://ojs.aaai.org/index.php/AAAI/article/view/10971",
  "Boosting Adversarial Attacks with Momentum": "http://openaccess.thecvf.com/content_cvpr_2018/html/Dong_Boosting_Adversarial_Attacks_CVPR_2018_paper.html",
  "Learning Visual Knowledge Memory Networks for Visual Question Answering": "https://openaccess.thecvf.com/content_cvpr_2018/html/Su_Learning_Visual_Knowledge_CVPR_2018_paper.html",
  "Towards Robust Detection of Adversarial Examples": "https://proceedings.neurips.cc/paper_files/paper/2018/hash/e0f7a4d0ef9b84b83b693bbf3feb8e6e-Abstract.html",
  "Composite Binary Decomposition Networks": "https://ojs.aaai.org/index.php/AAAI/article/view/4401",
  "DIAG-NRE: A Neural Pattern Diagnosis Framework for Distantly Supervised Neural Relation Extraction": "https://aclanthology.org/P19-1137/",
  "Efficient Decision-based Black-box Adversarial Attacks on Face Recognition": "https://openaccess.thecvf.com/content_CVPR_2019/html/Dong_Efficient_Decision-Based_Black-Box_Adversarial_Attacks_on_Face_Recognition_CVPR_2019_paper.html",
  "Evading Defenses to Transferable Adversarial Examples by Translation-Invariant Attacks": "https://www.openaccess.thecvf.com/content_CVPR_2019/html/Dong_Evading_Defenses_to_Transferable_Adversarial_Examples_by_Translation-Invariant_Attacks_CVPR_2019_paper.html",
  "Improving Black-box Adversarial Attacks with a Transfer-based Prior": "https://proceedings.neurips.cc/paper_files/paper/2019/hash/32508f53f24c46f685870a075eaaa29c-Abstract.html",
  "PrivPy: General and Scalable Privacy-Preserving Data Mining": "https://dl.acm.org/doi/10.1145/3292500.3330920",
  "Adversarial Distributional Training for Robust Deep Learning": "http://openaccess.thecvf.com/content_CVPR_2020/html/Dong_Benchmarking_Adversarial_Robustness_on_Image_Classification_CVPR_2020_paper.html",
  "Benchmarking Adversarial Robustness on Image Classification": "https://proceedings.neurips.cc/paper/2020/hash/5898d8095428ee310bf7fa3da1864ff7-Abstract.html",
  "Boosting Adversarial Training with Hypersphere Embedding": "https://openreview.net/forum?id=Byg9A24tvB",
  "Rethinking Softmax Cross-Entropy Loss for Adversarial Robustness": "https://proceedings.neurips.cc/paper_files/paper/2020/hash/aa85e45da94cb0d78853c50ba636a15a-Abstract.html",
  "Understanding and Exploring the Network with Stochastic Architectures": "https://proceedings.neurips.cc/paper_files/paper/2021/hash/16d11e9595188dbad0418a85f0351aba-Abstract.html",
  "Accumulative Poisoning Attacks on Real-time Data": "https://openreview.net/forum?id=Xb8xvrtB8Ce",
  "Bag of Tricks for Adversarial Training": "https://openaccess.thecvf.com/content/CVPR2021/html/Xiao_Improving_Transferability_of_Adversarial_Patches_on_Face_Recognition_With_Generative_CVPR_2021_paper.html",
  "Improving Transferability of Adversarial Patches on Face Recognition with Generative Models": "https://openreview.net/forum?id=MRwYiqfvs8",
  "Exploring Memorization in Adversarial Training": "https://proceedings.mlr.press/v162/hao22c.html",
  "GSmooth: Certified Robustness against Semantic Transformations via Generalized Randomized Smoothing": "https://proceedings.neurips.cc/paper_files/paper/2022/hash/7c818dd40651b420873af70b8a790e3f-Abstract-Conference.html",
  "Isometric 3D Adversarial Examples in the Physical World": "https://proceedings.neurips.cc/paper_files/paper/2022/hash/084727e8abf90a8365b940036329cb6f-Abstract-Conference.html",
  "Pre-trained Adversarial Perturbations": "https://openaccess.thecvf.com/content/CVPR2022/html/Pang_Two_Coupled_Rejection_Metrics_Can_Tell_Adversarial_Examples_Apart_CVPR_2022_paper.html",
  "Two Coupled Rejection Metrics Can Tell Adversarial Examples Apart": "https://proceedings.neurips.cc/paper_files/paper/2022/hash/eee7ae5cf0c4356c2aeca400771791aa-Abstract.html",
  "ViewFool: Evaluating the Robustness of Visual Recognition to Adversarial Viewpoints": "https://openaccess.thecvf.com/content/CVPR2023/html/Dong_Benchmarking_Robustness_of_3D_Object_Detection_to_Common_Corruptions_CVPR_2023_paper.html",
  "Benchmarking Robustness of 3D Object Detection to Common Corruptions in Autonomous Driving": "https://openaccess.thecvf.com/content/CVPR2023/html/Wang_Compacting_Binary_Neural_Networks_by_Sparse_Kernel_Selection_CVPR_2023_paper.html",
  "Compacting Binary Neural Networks by Sparse Kernel Selection": "https://proceedings.mlr.press/v202/hao23c",
  "GNOT: A General Neural Operator Transformer for Operator Learning": "https://proceedings.neurips.cc/paper_files/paper/2023/hash/50251f54848a433f3e47ae3b7cbded53-Abstract-Conference.html",
  "Learning Sample Difficulty from Pre-trained Models for Reliable Prediction": "https://openaccess.thecvf.com/content/CVPR2023/html/Zhu_Understanding_the_Robustness_of_3D_Object_Detection_With_Birds-Eye-View_Representations_CVPR_2023_paper.html",
  "Understanding the Robustness of 3D Object Detectors with Bird's-Eye-View Representations in Autonomous Driving": "https://openreview.net/forum?id=uXjfOmTiDt",
  "Embodied Active Defense: Leveraging Recurrent Feedback to Counter Adversarial Patches": "https://proceedings.mlr.press/v235/cheng24h.html",
  "Efficient Black-box Adversarial Attacks via Bayesian Optimization Guided by a Function Prior": "https://openaccess.thecvf.com/content/CVPR2024/html/Zhang_Exploring_the_Transferability_of_Visual_Prompting_for_Multimodal_Large_Language_CVPR_2024_paper.html",
  "Exploring the Transferability of Visual Prompting for Multimodal Large Language Models": "https://openaccess.thecvf.com/content/CVPR2024/html/Li_Focus_on_Hiders_Exploring_Hidden_Threats_for_Enhancing_Adversarial_Training_CVPR_2024_paper.html",
  "Focus on Hiders: Exploring Hidden Threats for Enhancing Adversarial Training": "https://icml.cc/virtual/2024/poster/34263",
  "Machine Vision Therapy: Multimodal Large Language Models Can Enhance Visual Robustness via Denoising In-Context Learning": "https://proceedings.neurips.cc/paper_files/paper/2024/hash/d81cb1f4dc6e13aeb45553f80b3d6837-Abstract-Conference.html",
  "MR-BEN: A Comprehensive Meta-Reasoning Benchmark for Large Language Models": "https://aclanthology.org/2024.findings-acl.876",
  "Preemptive Answer \"Attacks\" on Chain-of-Thought Reasoning": "https://proceedings.iclr.cc/paper_files/paper/2024/hash/53fe824f289060ce705ed7c01dae59d2-Abstract-Conference.html",
  "Rethinking Model Ensemble in Transfer-based Adversarial Attacks": "https://proceedings.mlr.press/v235/chen24k.html",
  "Robust Classification via a Single Diffusion Model": "https://aclanthology.org/2024.acl-long.858/",
  "The Earth is Flat because...: Investigating LLMs' Belief towards Misinformation via Persuasive Conversation": "https://proceedings.mlr.press/v235/zhu24i.html",
  "Toward Availability Attacks in 3D Point Clouds": "https://openaccess.thecvf.com/content/CVPR2024/html/Huang_Towards_Transferable_Targeted_3D_Adversarial_Attack_in_the_Physical_World_CVPR_2024_paper.html",
  "Towards Transferable Targeted 3D Adversarial Attack in the Physical World": "https://aclanthology.org/2025.acl-long.74/",
  "Jailbreak Large Vision-Language Models Through Multi-Modal Linkage": "https://aclanthology.org/2025.findings-acl.67/",
  "Nuclear Deployed!: Analyzing Catastrophic Risks in Decision-making of Autonomous LLM Agents": "https://icml.cc/virtual/2026/poster/63082",
  "AICrypto: A Comprehensive Benchmark For Evaluating Cryptography Capabilities of Large Language Models": "https://icml.cc/virtual/2026/poster/61291",
  "Reverse-Engineering Model Editing on Language Models": "https://arxiv.org/abs/2602.10134",
};
